name: Create Data

on:
  push:
    paths:
      - 'data.csv'
      - 'data_parser.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: Delete old files
        run: |
          rm  data/nodes.json
          rm  data/edges.json
          rm  data/data.json
          mkdir data
          ls
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python data_parser.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "create nodes and edges" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
